### PR TITLE
Projectile originate from weapon

### PR DESCRIPTION
**Pull request by echooff2**
I had to change the weapon system to make adding position where weapons shot easier. I could have used previous system and add get_shoot_pos() and hardcode the value but adding them would be hard. This system uses Position2D instead.
I included linting script that I use to lint files that are changed

### CODE REVIEW

**Comment by AWarmCupOfTea** [comment]
Not sure what's the point of introducing all these scene and removing pistol.gd script?

**Comment by echooff2** [comment]
I made all these scenes to make it more modular. To weapon node we can add reload scene and ammo scene and weapon will be reloadable, but one weapon might need different way of reloading or none, so we might add another reload and add this different reload or none at all and that weapon will have different reload  or none. One weapon might need to rotate only left/right so instead of giving that weapon rotate360.tscn we might make rotate_left_right.tscn and program that rotation. The same goes with all the weapon components nodes

**Comment by AWarmCupOfTea** [comment]
How would this handle if a weapon would need to override or supplement firing logic, for example? Before you could overwrite base_weapon, how would this work with the new approach?

**Comment by echooff2** [comment]
Pistol.tscn has nodes which are in components folder and they implement how weapons works. So if you don't include attack.tscn and instead create another attack scene with different attack script you can have different attack logic. Though attack.tscn have attack_scene script variable which you can set what projectile to shoot.

**Review by AWarmCupOfTea — APPROVED** [review]

**Pull request merged**
